# Generated by Django 2.2.3 on 2019-07-30 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(help_text='Enter a License Plate for you Crane', max_length=50)),
                ('trademark', models.CharField(help_text='Enter Trademark of you Crane', max_length=50)),
                ('year', models.IntegerField()),
                ('characteristic', models.CharField(help_text='Describe Crane characteristic', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your name', max_length=100)),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=100)),
                ('DPI', models.IntegerField(help_text='Enter your DPI', max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('o', 'On Route'), ('a', 'Available')], default='o', help_text='Crane availability', max_length=1)),
                ('crane_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tows.Crane')),
                ('pilot_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tows.Pilot')),
            ],
        ),
    ]
