# Generated by Django 2.2.3 on 2019-07-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tows', '0002_auto_20190730_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
