# Generated by Django 2.2.3 on 2019-07-30 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your name', max_length=100)),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=100)),
                ('address', models.CharField(help_text='Describe your Company Address', max_length=100)),
                ('phone', models.IntegerField(help_text='Enter Company Phone', max_length=8)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(help_text='Enter your password', max_length=50)),
                ('assign_crane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tows.Crane')),
            ],
        ),
    ]
